baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Kill Club | An independent production house"

[params]
description = "An independent production house telling stories through film, music and commercials."
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]