baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "KillClub. | Creative Production Company"

[params]
description = "Creative Production Company"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
