baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "The Masquerade | Trust No One"

[params]
description = "The Masquerade is an NFT brand driven by a mysterious story set in 1940s London - the height of the Blitz. "
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]